# Generated by Django 5.0.1 on 2024-01-31 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentDetails',
            new_name='AgentDetail',
        ),
        migrations.RenameField(
            model_name='agentdetail',
            old_name='propertyCost',
            new_name='property_cost',
        ),
        migrations.RenameField(
            model_name='agentdetail',
            old_name='propertyLocation',
            new_name='property_location',
        ),
        migrations.RenameField(
            model_name='agentdetail',
            old_name='propertyRequirements',
            new_name='property_requirements',
        ),
        migrations.RenameField(
            model_name='agentdetail',
            old_name='propertyTitle',
            new_name='property_title',
        ),
        migrations.RenameField(
            model_name='agentdetail',
            old_name='propertyType',
            new_name='property_type',
        ),
    ]
